spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.use-new-id-generator-mappings: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${db.host:localhost}:${db.port:3306}/store_ms_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
    username: root
    password: adminadmin
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
        
msg: 'Welcome from cloud configuration - Development Environment.'
